version: '3.8'

services:
  db:
    container_name: certificate
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:  certificate
    ports:
      - "5433:5432"